created home route
facn2/judgement-day pull request #9
Opened 2017-08-22 15:24 UTC by Wyrd00

relates #8
hurry up mario

2017-08-22 15:26 UTC, matthewdking requested changes

2017-08-22 15:26 UTC, matthewdking commented on package.json
> +    "tape": "^4.8.0"
tape, tap-spec and install should be dev dependencies

2017-08-22 15:31 UTC, matthewdking approved these changes
:tada:

2017-08-22 15:32 UTC, sajedazoabi approved these changes

2017-08-23 07:06 UTC, matthewdking commented
@Karyum :hourglass_flowing_sand:

2017-08-23 07:07 UTC, Karyum reviewed
good job you guys just a really smal change :+1:

2017-08-23 07:07 UTC, Karyum commented on src/controllers/home.js
> +	res.render('home', { activePage: {home: true}});
copy pasting workshop much? :stuck_out_tongue_winking_eye:

2017-08-23 07:07 UTC, Karyum commented on src/views/error.hbs
> +	<main class="main">
indentation is wierd here

2017-08-23 07:07 UTC, Karyum commented on src/views/home.hbs
> +	<h1 class="main__title">HOME</h1>
and here

2017-08-23 07:07 UTC, Karyum commented on src/views/layouts/main.hbs
> +		{{{body}}}
and here

2017-08-23 07:07 UTC, Karyum commented
@matthewdking :hourglass_flowing_sand:

2017-08-23 07:09 UTC, matthewdking commented
@Karyum :hourglass: :hourglass: :hourglass:

2017-08-23 07:20 UTC, Wyrd00 commented on src/controllers/home.js
> +	res.render('home', { activePage: {home: true}});
gasp slander!

2017-08-23 07:36 UTC, Karyum approved these changes
sneaked in couple of images i saw that :eyes:

2017-08-23 07:36 UTC, merged